version: '3.9' # Manteniamo la tua versione 3.9

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: smartdoctor_postgres
    environment:
      - POSTGRES_DB=smartdoctor_db
      - POSTGRES_USER=sd_user
      - POSTGRES_PASSWORD=sd_password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume per la persistenza
    restart: always
  smartdoctor:
    build: .
    container_name: smartdoctor_cron_job
    environment:
      - TELEGRAM_TOKEN=8373401994:AAEN9aXHFvkiSL2pu_SUmkHVnhqAzvYLiPM
      - TELEGRAM_CHAT_ID=1087544555
